katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('katalog/', include('katalog.urls')),
    path('todolist/', include('todolist.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('', include('example_app.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import deletetask, finishtask, show_todolist, register, login_user, logout_user, create_task, get_todolist_json, add_todolist_item, deleteTask



app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'), 
    path('create-task/', create_task, name='create_task'),
    path('add/', add_todolist_item, name='add_todolist_item'),
    path('finishtask/<int:pk>', finishtask, name='finishtask'),
    path('json/', get_todolist_json, name='get_todolist_json'),
    path('deletetask/<int:pk>', deletetask, name='deletetask'),
    path('delete/<int:pk>', deleteTask,name='deleteTask')
    # path('xml/', show_mywatchlist_xml, name='show_mywatchlist_xml'),
    # path('json/', show_mywatchlist_json, name='show_mywatchlist_json'),
    # path('html/', show_mywatchlist, name='show_mywatchlist'),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/views.py
from django.shortcuts import render
from todolist.models import Task

from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt



#
def get_todolist_json(request):
    todolist_item = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', todolist_item))


# TODO: belom bener
def add_todolist_item(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        description = request.POST.get("description")

        new_barang = Task(user=request.user, title=title, description=description, date=datetime.datetime.now(), is_finished=False)
        new_barang.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt 
def deleteTask(request, pk):
    if request.method =='DELETE' :
        task_selected = Task.objects.get(id=pk)
        Task.delete(task_selected)

        return JsonResponse(b"DELETED", status=201)
    

    


# Show html function
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    list_task = Task.objects.filter(user= request.user)

    # transfer data from database to html
    context = {
        'list_task' : list_task,
        'name' : 'Trias Ahmad Fairuz',
        'id' : '2106633645',
        'last_login': request.COOKIES['last_login'],
        'username' : request.user.username,
    }
    return render(request, "todolist.html", context)

# create new task function
def create_task(request):
    if request.method == 'POST':
        # get the information needed to create a Task object from html form
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        Task.objects.create(title=title, description=description, date=date, user=user, is_finished=False)
        return redirect('todolist:show_todolist')

    return render(request, "create_task.html")

# finish task function
def finishtask(request, pk):
    task_selected = Task.objects.get(id=pk)
    task_selected.is_finished = True
    task_selected.save()
    return redirect('todolist:show_todolist')

# delete task function
def deletetask(request, pk):
    task_selected = Task.objects.get(id=pk)
    Task.delete(task_selected)
    return redirect('todolist:show_todolist')


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Todo List</title>
{% endblock meta %}

{% block content %}



<div class = "create_task">
    <form method="POST" action="">
        {% csrf_token %}
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-60 col-lg-6 col-xl-5">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <div class="mb-md-20 mt-md-20 pb-50">
          
                        <h2 class="fw-bold mb-2 text-uppercase">Create Task</h2>
                        <table class="text-start table table-borderless vertical-align form-control" style="font-size: small;">  

                            <tr class="form-outline form-white mb-4">
                                <td>
                                    Title

                                </td>
                                <td>
                                    <input type="text" name="title" id="typeTitle" class="form-control" />
                                    
                                </td>
                            </tr>
                            <tr class="form-outline form-white mb-4">  
                                <td>
                                    Description
                                </td>
                                <td>
                                    <input type="text" name="description" id="typeDescription" class="form-control" />
                                </td>
                            </tr>  
                        </table>

                        <input class="btn login_btn btn btn-primary form-control" type="submit" name="submit" value="Create!"/>

    

          
                      </div>
          
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    </form>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}


{% block meta %}
<title>Login</title>

{% endblock meta %}

{% block content %}

<!-- <div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div> -->

<!-- <style>
    .login {
    color: rgb(0, 0, 0); 
    padding: 10px; 
    font-family: 'verdana';
    text-align: center;
    background-image: linear-gradient(90deg, #FA8BFF 0%, #2BD2FF 52%, #2BFF88 90%);

}
</style> -->

<div class = "login">
    <form method="POST" action="">
        {% csrf_token %}
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <div class="mb-md-5 mt-md-4 pb-5">
          
                        <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                        <p class="text-white-50 mb-5">Please enter your username and password!</p>
          
                        <div class="form-outline form-white mb-4">
                          <input type="text" name="username" id="typeUsername" class="form-control" />
                          <label class="form-label" for="typeUsername">Username</label>
                        </div>
          
                        <div class="form-outline form-white mb-4">
                          <input type="password" name="password" id="typePasswordX" class="form-control" />
                          <label class="form-label" for="typePasswordX">Password</label>
                        </div>
          
          
                        <input class="btn btn-outline-light btn-lg px-5" type="submit" value="Login"></input>
          
                      </div>
    
                      <div style="text-align: center;">
                        {% if messages %}
                        <ul>
                       {% for message in messages %}
                       <div class="alert alert-danger" role="alert">
                           {{ message }}
                       </div>
                       {% endfor %}
                        </ul>
                       {% endif %}
                      </div>
        
    
          
                      <div>
                        <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                        </p>
                      </div>
          
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    </form>
</div>



{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}

<!-- <div class = "register">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div> -->
<div class="register">
    <form method="POST" action="">
        {% csrf_token %}
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center
                    h-100">
                    <div class="col-12 col-md-60 col-lg-6 col-xl-5">
                        <div class="card bg-dark text-white"
                            style="border-radius: 1rem;">
                            <div class="card-body p-5 text-center">

                                <div class="mb-md-20 mt-md-20 pb-50">

                                    <h2 class="fw-bold mb-2 text-uppercase">Registration</h2>
                                    <table class="text-start table
                                        table-borderless vertical-align
                                        form-control" style="font-size: small;">
                                        {{ form.as_table }}

                                    </table>

                                    <input class="btn login_btn btn btn-primary
                                        form-control" type="submit"
                                        name="submit" value="Create!"/>

                                </div>

                                <div style="text-align: center;">
                                    {% if messages %}
                                    <ul>
                                        {% for message in messages %}
                                        <div class="alert alert-danger"
                                            role="alert">
                                            {{ message }}
                                        </div>
                                        {% endfor %}
                                    </ul>
                                    {% endif %}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<h1>Assignment 4 PBP/PBD</h1>


<h4>Selamat Datang, {{username}}</h4>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Add task</button>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">New Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="formtask">
            {% csrf_token %}
            <div class="mb-3">
              <label for="recipient-name" class="col-form-label">Title:</label>
              <input type="text" class="form-control" id="field_title" name="title">
            </div>
            <div class="mb-3">
              <label for="message-text" class="col-form-label">Description:</label>
              <textarea class="form-control" id="field_desc" name="description"></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="addtaskbutton" data-bs-dismiss="modal">Add</button>
        </div>
      </div>
    </div>
  </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function()  {
    refreshTodolist();
  });
  
  async function getTodolist() {
    return fetch("{% url 'todolist:get_todolist_json' %}").then((res) => res.json())
  }

  async function refreshTodolist() {
        document.getElementById("cardcontainer").innerHTML = ""
        const todolist = await getTodolist()
        let htmlString = ``
        todolist.forEach((item) => {
          htmlString += `<div class="col-md-4">
      <div class="card" style="width: 18rem;">
        <img src="https://drive.google.com/uc?export=view&id=17KEpEig6Y5PX9nUwZl1INRzj9Xuuz9NS" class="card-img-top"
          alt="...">
        <div class="card-body">
          <h5 class="card-title">${item.fields.title}</h5>
          <h6 class="card-subtitle mb-2 text-muted">${item.fields.date}</h6>
          <p class="card-text">${item.fields.description}</p>
          <p class="card-text"></p> 
          {% if task.is_finished %}
          <p class="card-text">Finished</p>
          {% else %}
          <p class="card-text">Not Finished</p>
          {% endif %}
          
          
          
        </div>
      </div>
    </div>` 
        })
        
        document.getElementById("cardcontainer").innerHTML = htmlString
  }

  function addTodolist() {
    fetch("{% url 'todolist:add_todolist_item' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#formtask'))
      }).then(refreshTodolist)
    return false
  }

  // function deleteTask(val) {
  //   console.log(111);
  //   fetch(`{% url 'todolist:deleteTask' 1 %}`, {
  //     method: "DELETE"
  //   }).then(refreshTodolist)
  // }

  document.getElementById("addtaskbutton").onclick = addTodolist
  
  refreshTodolist()
</script>

<div class="container mx-auto mt-4">
  <div class="row" id="cardcontainer">

  </div>
</div>

<!-- <h5>Sesi terakhir login: {{ last_login }}</h5> -->

<button><a href="{% url 'todolist:logout' %}">Logout</a></button>

{% endblock content %}